/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          bg: '#0f172a',
          surface: '#1e293b',
          border: '#334155',
          text: '#f1f5f9',
          muted: '#94a3b8',
        },
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#e7bdb1",
        "primary-container": "#8f6d63",
        "on-primary-container": "#fffcff",
        "inverse-surface": "#2f312f",
        "primary": "#74554b",
        "surface-container-high": "#e9e8e5",
        "surface-variant": "#e3e2e0",
        "surface-container-highest": "#e3e2e0",
        "secondary-container": "#ffdb94",
        "on-secondary-fixed-variant": "#5a4309",
        "surface": "#faf9f6",
        "surface-container-low": "#f4f3f1",
        "on-secondary-container": "#795f24",
        "on-surface": "#1a1c1a",
        "primary-fixed": "#ffdbd0",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f2f1ee",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "background": "#faf9f6",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#2c160e",
        "tertiary-container": "#7f7363",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dbdad7",
        "surface-tint": "#77574d",
        "on-tertiary-container": "#fffcff",
        "tertiary-fixed-dim": "#d3c4b2",
        "secondary": "#745b20",
        "outline-variant": "#d4c3be",
        "on-secondary-fixed": "#261a00",
        "tertiary-fixed": "#efe0cd",
        "on-tertiary-fixed-variant": "#4f4537",
        "on-background": "#1a1c1a",
        "tertiary": "#655b4c",
        "secondary-fixed-dim": "#e4c27d",
        "secondary-fixed": "#ffdf9f",
        "on-primary-fixed-variant": "#5d4037",
        "on-surface-variant": "#504441",
        "surface-bright": "#faf9f6",
        "surface-container": "#efeeeb",
        "error-container": "#ffdad6",
        "outline": "#827470",
        "inverse-primary": "#e7bdb1",
        "on-tertiary-fixed": "#221a0f",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
